import type { ColumnDef } from '../types/column';

export const ALL_COLUMNS: ColumnDef[] = [
  { key: 'nickName',                    label: 'Nome',                   group: 'original', defaultVisible: true,  pinned: true,  sortable: 'nickName' },
  { key: 'code',                        label: 'Código',                 group: 'original', defaultVisible: false,                sortable: 'code' },
  { key: 'product',                     label: 'Produto',                group: 'original', defaultVisible: false,                sortable: 'product' },
  { key: 'fee',                         label: 'Taxa',                   group: 'original', defaultVisible: true,                 sortable: 'fee' },
  { key: 'maturityDate',                label: 'Vencimento',             group: 'original', defaultVisible: true,                 sortable: 'maturityDate' },
  { key: 'puMinValue',                  label: 'PU Mínimo',              group: 'original', defaultVisible: true,                 sortable: 'puMinValue' },
  { key: 'paymentVsPuMin',              label: 'Média Pagto/PU',         group: 'custom',   defaultVisible: false,                sortable: 'paymentVsPuMin' },
  { key: 'minimumQuantityForApplication', label: 'Qtd. Mín. Aplicação', group: 'original', defaultVisible: false },
  { key: 'quantityAvailable',           label: 'Qtd. Disponível',       group: 'original', defaultVisible: true,                 sortable: 'quantityAvailable' },
  { key: 'indexers',                    label: 'Indexadores',            group: 'original', defaultVisible: false },
  { key: 'ratingName',                  label: 'Rating',                 group: 'original', defaultVisible: true,                 sortable: 'ratingName' },
  { key: 'agencyName',                  label: 'Agência',                group: 'original', defaultVisible: false },
  { key: 'riskScore',                   label: 'Risco',                  group: 'original', defaultVisible: true,                 sortable: 'riskScore' },
  { key: 'descriptionInterestrates',    label: 'Juros',                  group: 'original', defaultVisible: true },
  { key: 'descriptionAmortization',     label: 'Amortização',            group: 'original', defaultVisible: true },
  { key: 'graceDate',                   label: 'Data Carência',          group: 'original', defaultVisible: false },
  { key: 'redemptionType',              label: 'Tipo Resgate',           group: 'original', defaultVisible: false },
  { key: 'incentive',                   label: 'Incentivado',            group: 'original', defaultVisible: false },
  { key: 'guaranteeFGC',                label: 'Garantia FGC',           group: 'original', defaultVisible: false },
  { key: 'qualifiedInvestor',           label: 'Inv. Qualificado',       group: 'original', defaultVisible: false },
  { key: 'professionalInvestor',        label: 'Inv. Profissional',      group: 'original', defaultVisible: false },
  { key: 'generalInvestor',             label: 'Inv. Geral',             group: 'original', defaultVisible: false },
  { key: 'prefixedFeeValue',            label: 'Taxa Prefixada',         group: 'original', defaultVisible: false },
  { key: 'b3Code',                      label: 'Código B3',              group: 'custom',   defaultVisible: true,                 sortable: 'b3Code' },
  { key: 'fiduciaryAgentUrl',           label: 'Ag. Fiduciário',         group: 'custom',   defaultVisible: true },
  { key: 'notes',                       label: 'Notas',                  group: 'custom',   defaultVisible: false },
  { key: 'favorite',                    label: 'Favorito',               group: 'custom',   defaultVisible: false },
  { key: 'tags',                        label: 'Tags',                   group: 'custom',   defaultVisible: false },
  { key: 'trackingStatus',              label: 'Status',                 group: 'custom',   defaultVisible: false },
  { key: 'actions',                     label: 'Ações',                  group: 'ui',       defaultVisible: true,  pinned: true },
];
